### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by ericfourrier** [ericfourrier/pandas-patch#2]
### Task
- [ ] outliers detection.

**Comment by ericfourrier** [comment]
### Task
- [ ] mathplotlib visu. Kevin

**Comment by ericfourrier** [comment]
### Task 

- [ ] stack function. Eric
- [ ] more complete summary function Eric
